apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: {{ .Values.replicas }} 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: {{ .Values.imageName }} 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: my-app-service
spec:
  ports:
    - protocol: TCP
      nodePort: {{ .Values.nodePort }}
      port: 8080
      targetPort: 8080
  selector:
    app: my-app
  type: NodePort